### ISSUE TITLE
Question about detouring virtual function

### ISSUE THREAD

**Issue by dankmolot** [danielga/detouring#12]
Hello, I'm trying to detour virtual function `GarrysMod::Lua::ILuaInterface::Cycle` on windows by using `Detouring::ClassProxy`. On win32 build (main branch) everything successfully detours, but on x64 build (x86-64 branch) function not called (but `Hook(...)` returns true).

As I found in [`Detouring::GetVirtualAddress`](https://github.com/danielga/detouring/blob/02860d0dcfa66c92b6193b0d43e69f413eaf0f47/include/detouring/helpers.hpp#L228) variable `addr` is `0xFF` on win32 build, and `0xE9` on x64 build. Because of this check for jmp function fails, [iterating over vtable](https://github.com/danielga/detouring/blob/02860d0dcfa66c92b6193b0d43e69f413eaf0f47/include/detouring/helpers.hpp#L268) also fails, then `ClassProxy::Hook` tries to hook function by using `Detouring::Hook`, and returns true, but function isn't called.

As I found myself, `0xFF` is opcode for jump to absolute address, and `0xE9` is opcode for jump to relative address. Is there are solution fix detouring on x64 build? Thank you in advance.

**Comment by danielga** [comment]
I've stopped supporting the x86-64 branch, until Facepunch becomes serious and makes it official, no betas.

**Comment by RaphaelIT7** [comment]
@danielga Is this still an issue I should worry about, or did you fix this at some point?
I plan to do more on 64x related things especially with ClassProxy & randomly saw this issue.
