### ISSUE TITLE
Question regarding usage and functions that are exported in a dll such as lua_shared or tier0

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/detouring#8]
So I'm just wanting clarification but would this repository be useful for modifying how a function behaves. for example modifying the Exported MsgC function of teir0 to instead return reveresed text, and have it where if any place in the engine called the MsgC() function it would always be reverse text, just for a simple example.

Would this tool be usefull for achieving that sort of stuff? or is it more for detouring lua functions inside c++? Or would it only work inside the module using this itself?

**Comment by danielga** [comment]
The former. When you apply a detour in code, it's a global thing, which would be dangerous in the usual Source games because of VAC but not a problem in Garry's Mod.

**Comment by VaasKahnGrim** [comment]
ah perfect, thats exactly what I've been looking for then. thanks dude
